docs_dir: .

# Project information
site_name: satcube
site_url: https://andesdatacube.github.io/satcube/
site_author: AndesDataCube
site_description: satcube turns scattered Sentinel-2 imagery into clean, aligned and super-resolved data cubes.

# Repository
repo_url: https://github.com/andesdatacube/satcube
repo_name: andesdatacube/satcube
use_directory_urls: false

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: https://huggingface.co/datasets/JulioContrerasH/DataMLSTAC/resolve/main/logo_satcube.png
  favicon: https://huggingface.co/datasets/JulioContrerasH/DataMLSTAC/resolve/main/logo_satcube.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide
    - content.code.copy
    - content.code.annotate

# Page tree
nav:
  - Home: README.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Pipeline: pipeline.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md
  - Code of conduct: CODE_OF_CONDUCT.md

# Plugins
plugins:
  - search
  - same-dir
  - awesome-pages

# Markdown extensions
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists
  - toc:
      permalink: true

# Extra CSS (descomenta si creas docs/style/style.css)
extra_css:
  - docs/style/style.css